import React,{useState,useEffect,useMemo} from "react";
import{Orbit,Flame,Sparkles,ArrowRight,ArrowUpRight,Plus,Search,Check,CheckCircle2,ShieldCheck,Lightbulb,Users,HeartHandshake,Github,ExternalLink,BookOpen,Compass,Menu,X,Clipboard,Atom,Archive}from"lucide-react";
import{categories,examples,stages,checks,score,level,parseIssue,makeIssue}from"./data.js";
import Bubbleverse from "./Bubbleverse.jsx";
import BubbleRoom from "./BubbleRoom.jsx";
import ClaimArena from "./ClaimArena.jsx";
import BubbleFusion from "./BubbleFusion.jsx";
import OfflineCapsuleLab from "./OfflineCapsuleLab.jsx";
import {parseFusionIssue} from "./fusionData.js";
import {parseFusionResponseIssue} from "./fusionResponses.js";
import {parseCharterIssue} from "./fusionCharters.js";
import {parseTrialIssue} from "./fusionTrials.js";
import {parseArtifactIssue} from "./artifactData.js";
import {parseByteCheckIssue} from "./byteChecks.js";
import {parseReproductionIssue} from "./reproductionData.js";
import {parseAnchorIssue} from "./dossierAnchor.js";
import {parseFlameChallenge} from "./flameData.js";
import {parseEvolutionIssue} from "./evolutionData.js";
import {parseEvidenceIssue} from "./evidenceData.js";
import {parseReviewIssue} from "./reviewData.js";
import {parseRoomEntry,roomIdFromHash,bubbleRoomPath} from "./roomData.js";
import "./styles.css";
const repo="https://github.com/MichaelWave369/bubblenest";
const api="https://api.github.com/repos/MichaelWave369/bubblenest/issues?state=all&per_page=100&page=";
const blank={title:"",category:"Science",summary:"",why:"",ask:"",evidence:""};
const pages=[["home","The Nest",Orbit],["explore","Explore",Compass],["bubbleverse","Bubbleverse",Orbit],["fusion","Bubble Fusion",HeartHandshake],["capsules","Capsule Lab",Archive],["flame","Claim to Flame",Flame],["about","Philosophy",BookOpen]];
const initialPage=()=>{const h=location.hash.replace(/^#\/?/,"").split("?")[0];return h.startsWith("room/")?"room":pages.some(x=>x[0]===h)?h:"home";};
function Logo(){return <span className="logo-orbit" aria-hidden="true"><i/><i/><i/></span>}
function Tag({children}){return <span className="eyebrow"><Sparkles size={13}/>{children}</span>}
function BubbleCard({b,onOpen}){return <article className="bubble-card"><div className="card-orbit" aria-hidden="true"><i/><i/><i/></div><div className="card-top"><span className="pill">{b.category}</span><span className="card-flag">{b.sample?"EXAMPLE":b.local?"PRIVATE DRAFT":"PUBLIC BUBBLE"}</span></div><h3>{b.title}</h3><p>{b.summary}</p><div className="card-bottom"><span><Users size={14}/>{b.author}</span><button aria-label={"Open "+b.title} onClick={onOpen}><ArrowUpRight size={19}/></button></div></article>}
function App(){
 const[page,setPage]=useState(initialPage),[menu,setMenu]=useState(false),[compose,setCompose]=useState(false),[detail,setDetail]=useState(null),[category,setCategory]=useState("All"),[query,setQuery]=useState("");
 const[form,setForm]=useState(blank),[claim,setClaim]=useState(""),[checked,setChecked]=useState({}),[copied,setCopied]=useState(false);
 const[drafts,setDrafts]=useState(()=>{try{return JSON.parse(localStorage.getItem("bubblenest-drafts-v1")||"[]")}catch{return[]}});
 const[remote,setRemote]=useState([]),[roomEntries,setRoomEntries]=useState([]),[evolutionEvents,setEvolutionEvents]=useState([]),[evidenceEntries,setEvidenceEntries]=useState([]),[reviewEntries,setReviewEntries]=useState([]),[flameChallenges,setFlameChallenges]=useState([]),[fusionInvitations,setFusionInvitations]=useState([]),[fusionResponses,setFusionResponses]=useState([]),[fusionCharters,setFusionCharters]=useState([]),[fusionTrials,setFusionTrials]=useState([]),[fusionArtifacts,setFusionArtifacts]=useState([]),[artifactByteChecks,setArtifactByteChecks]=useState([]),[fusionReproductions,setFusionReproductions]=useState([]),[dossierAnchors,setDossierAnchors]=useState([]),[feedStatus,setFeedStatus]=useState("loading");
 useEffect(()=>{const listener=()=>{setPage(initialPage());setMenu(false)};window.addEventListener("hashchange",listener);return()=>window.removeEventListener("hashchange",listener)},[]);
 useEffect(()=>{let on=true;(async()=>{try{const all=[];for(let page=1;page<=3;page++){const response=await fetch(api+page,{headers:{Accept:"application/vnd.github+json"}});if(!response.ok)throw Error("GitHub API unavailable");const data=await response.json();all.push(...data);if(data.length<100)break;}if(on){setRemote(all.map(parseIssue).filter(Boolean));setRoomEntries(all.map(parseRoomEntry).filter(Boolean));setEvolutionEvents(all.map(parseEvolutionIssue).filter(Boolean));setEvidenceEntries(all.map(parseEvidenceIssue).filter(Boolean));setReviewEntries(all.map(parseReviewIssue).filter(Boolean));setFlameChallenges(all.map(parseFlameChallenge).filter(Boolean));setFusionInvitations(all.map(parseFusionIssue).filter(Boolean));setFusionResponses(all.map(parseFusionResponseIssue).filter(Boolean));setFusionCharters(all.map(parseCharterIssue).filter(Boolean));setFusionTrials(all.map(parseTrialIssue).filter(Boolean));setFusionArtifacts(all.map(parseArtifactIssue).filter(Boolean));setArtifactByteChecks(all.map(parseByteCheckIssue).filter(Boolean));setFusionReproductions(all.map(parseReproductionIssue).filter(Boolean));setDossierAnchors(all.map(parseAnchorIssue).filter(Boolean));setFeedStatus("ready");}}catch{if(on)setFeedStatus("unavailable")}})();return()=>{on=false}},[]);
 useEffect(()=>{try{localStorage.setItem("bubblenest-drafts-v1",JSON.stringify(drafts))}catch{}},[drafts]);
 useEffect(()=>{document.body.style.overflow=compose||detail?"hidden":"";return()=>{document.body.style.overflow=""}},[compose,detail]);
 const navigate=p=>{location.hash="/"+p;setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const openRoom=b=>{location.hash=bubbleRoomPath(b.id);setPage("room");setDetail(null);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const bubbles=useMemo(()=>[...remote,...drafts.map(b=>({...b,local:true,author:"Only you"})),...examples],[remote,drafts]);
 const found=useMemo(()=>bubbles.filter(b=>(category==="All"||b.category===category)&&[b.title,b.summary,b.author,b.category].join(" ").toLowerCase().includes(query.toLowerCase())),[bubbles,category,query]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 const canPost=!!(form.title.trim()&&form.summary.trim()&&form.ask.trim());
 const save=()=>{if(!canPost)return;setDrafts(d=>[{...form,id:"draft-"+Date.now()},...d].slice(0,25));setCompose(false);setForm(blank);navigate("explore")};
 const publish=()=>{if(!canPost)return;const url=repo+"/issues/new?title="+encodeURIComponent("[Bubble] "+form.title.trim())+"&body="+encodeURIComponent(makeIssue(form));window.open(url,"_blank","noopener,noreferrer")};
 const points=score(checked),stage=level(points);
 const copyReport=async()=>{let lines=["CLAIM TO FLAME | SAUCE BEFORE SOURCE","Claim: "+(claim||"(not specified)"),"Evidence self-check: "+points+"/100 | "+stage.name,...checks.map(c=>(checked[c.id]?"[x] ":"[ ] ")+c.label),"Note: self-reported evidence completeness, NOT proof of truth."];try{await navigator.clipboard.writeText(lines.join("\n"));setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 return <div className="app">
  <div className="background-stars" aria-hidden="true"/><div className="glow glow-a"/><div className="glow glow-b"/>
  <header className="header"><a className="brand" href="#/home"><Logo/><span><strong>bubble<span>nest</span></strong><small>Where ideas find each other</small></span></a><nav className={menu?"nav open":"nav"} aria-label="Main navigation">{pages.map(([id,name,Icon])=><a key={id} className={page===id?"active":""} href={"#/"+id} onClick={()=>{setPage(id);setMenu(false)}}><Icon size={16}/>{name}</a>)}</nav><div className="nav-actions"><button className="top-button" onClick={()=>setCompose(true)}><Plus size={17}/> Start a bubble</button><button aria-label="Toggle menu" aria-expanded={menu} className="menu-button" onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></header>
  <main id="main">
  {page==="home"&&<>
   <section className="hero"><div className="hero-copy"><Tag>THE OPEN COLLABORATION COMMONS</Tag><h1>Big ideas<br/>start as <em>little<br/>bubbles.</em></h1><p>Bring the weird theory. The unfinished sketch. The impossible question. Find people and agents who want to build, test, and grow it with you.</p><div className="actions"><button className="button primary" onClick={()=>setCompose(true)}><Sparkles size={18}/> Start a bubble <ArrowRight size={18}/></button><button className="button plain" onClick={()=>navigate("explore")}>Explore the commons <ArrowUpRight size={17}/></button></div><div className="promises"><span><CheckCircle2 size={15}/> Open ideas</span><span><CheckCircle2 size={15}/> Honest evidence</span><span><CheckCircle2 size={15}/> Humans + agents</span></div></div><div className="hero-art"><div className="ring ring-a"/><div className="ring ring-b"/><div className="ring ring-c"/><span className="planet planet-a"/><span className="planet planet-b"/><span className="planet planet-c"/><span className="planet planet-d"/><div className="central-bubble"><Logo/><strong>Every idea<br/>needs a nest.</strong><small>CONNECT · QUESTION · CREATE</small></div><div className="float-label label-a"><Lightbulb size={17}/> spark</div><div className="float-label label-b"><Atom size={17}/> theory</div><div className="float-label label-c"><HeartHandshake size={17}/> collab</div></div></section>
   <div className="step-strip"><div><b>01</b><span>Start with a spark</span></div><div><b>02</b><span>Grow it together</span></div><div><b>03</b><span>Bring the receipts</span></div><div><b>∞</b><span>Possible connections</span></div></div>
   <section className="section"><div className="section-head"><div><Tag>THE IDEA COMMONS</Tag><h2>Find a bubble to <em>join.</em></h2><p>Browse illustrative sparks and real public discussions.</p></div><button className="text-button" onClick={()=>navigate("explore")}>Explore all <ArrowRight size={16}/></button></div><div className="card-grid">{bubbles.slice(0,3).map(b=><BubbleCard key={b.id} b={b} onOpen={()=>openRoom(b)}/>)}</div></section>
   <section className="bv-feature"><div className="bv-feature-art"><Orbit size={66}/></div><div className="bv-feature-copy"><span className="eyebrow"><Sparkles size={13}/> THE LIVING IDEA ATLAS</span><h2>Enter the <em>Bubbleverse.</em></h2><p>Explore neighboring ideas, compare possible overlaps and preserve independent attribution.</p></div><button className="button primary" onClick={()=>navigate("bubbleverse")}>Explore the map <ArrowRight size={17}/></button></section>
   <section className="flame-feature"><div className="feature-icon"><Flame size={78}/><span>THE EVIDENCE LAB</span></div><div><Tag>THE ROYAL SOCIETY PRESENTS</Tag><h2>Claim to <em>Flame.</em></h2><h3>SAUCE BEFORE SOURCE.</h3><p>Bring a claim. Turn up the scrutiny. Go from Weak Sauce to Ledger Reaper and learn which receipts are still missing.</p><button className="button warm" onClick={()=>navigate("flame")}>Enter the sauce lab <ArrowRight size={17}/></button></div></section>
   <section className="manifesto"><div>✳</div><h2>Wild ideas welcome.<br/><em>Unsupported certainty, not so much.</em></h2><p>Curiosity first. Clear credit. Honest sourcing. Respect for the people behind each idea.</p></section>
  </>}
  {page==="bubbleverse"&&<Bubbleverse bubbles={bubbles} onOpen={setDetail} onRoom={openRoom} onNew={()=>setCompose(true)}/>}
  {page==="capsules"&&<OfflineCapsuleLab/>}
  {page==="fusion"&&<BubbleFusion bubbles={bubbles} proposals={fusionInvitations} responses={fusionResponses} charters={fusionCharters} trials={fusionTrials} artifacts={fusionArtifacts} byteChecks={artifactByteChecks} reproductions={fusionReproductions} anchors={dossierAnchors} feedStatus={feedStatus} onOpenRoom={openRoom}/>}
  {page==="room"&&<BubbleRoom roomId={roomIdFromHash(location.hash)} bubble={bubbles.find(b=>String(b.id)===roomIdFromHash(location.hash))} allEntries={roomEntries} evolutionEvents={evolutionEvents} evidenceEntries={evidenceEntries} reviewEntries={reviewEntries} flameChallenges={flameChallenges} fusionInvitations={fusionInvitations} allBubbles={bubbles} feedStatus={feedStatus} onBack={()=>navigate("explore")} onStart={()=>setCompose(true)}/>}
  {page==="explore"&&<section className="inner-page"><Tag>THE LIVING COMMONS</Tag><div className="page-heading"><div><h1>Explore the <em>bubbles.</em></h1><p>Follow an idea, collaborate on GitHub, or start one of your own.</p></div><button className="button primary" onClick={()=>setCompose(true)}><Plus size={17}/> Start a bubble</button></div><div className="filters"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, topics, authors..." aria-label="Search bubbles"/></label><div className="chips">{categories.map(c=><button key={c} className={category===c?"chip active":"chip"} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="feed-line"><span>{feedStatus==="loading"?"Checking GitHub for public bubbles...":feedStatus==="unavailable"?"GitHub API unavailable; examples and drafts are still accessible.":remote.length+" public community bubble(s) loaded."}</span><span>{found.length} shown</span></div><div className="card-grid">{found.map(b=><BubbleCard key={b.id} b={b} onOpen={()=>openRoom(b)}/>)}</div>{found.length===0&&<div className="no-results"><Orbit size={36}/><h3>Nothing in this orbit yet.</h3><p>Try another filter or start something new.</p></div>}<div className="notice"><ShieldCheck size={19}/><p><strong>Real collaboration, honest limitations:</strong> The website lists public GitHub Issues matching Bubble Nest's submission format. Public posting uses GitHub sign-in. Local drafts never leave this browser unless you publish them yourself. Sample bubbles are marked EXAMPLE.</p></div></section>}
  {page==="flame"&&<section className="inner-page flame-page"><Tag>THE EVIDENCE LAB · OFFICIALLY UNOFFICIAL</Tag><div className="flame-heading"><div><h1>Claim to <em>Flame.</em></h1><strong>SAUCE BEFORE SOURCE.</strong><p>Every claim deserves questions. Each hotter sauce represents stronger documented evidence, not louder confidence.</p></div><div className="big-flame"><Flame size={80}/><span>LEDGER ABOVE BRUV</span></div></div><div className="sauces">{stages.map((s,i)=><div className={stage.name===s.name?"sauce current":"sauce"} key={s.name} style={{"--sauce":s.color}}><div className="bottle"><div className="cap"/><div className="glass"><Flame size={i>3?24:18}/><small>{String(i+1).padStart(2,"0")}</small></div></div><b>{s.name}</b><span>{s.sub}</span></div>)}</div><div className="lab-grid"><div className="lab-card"><Tag>THE BRUV-O-METER™</Tag><h2>Inspect your claim.</h2><label className="field-label" htmlFor="claim">What's the claim?</label><textarea id="claim" rows="3" maxLength="600" placeholder="Two paths can arrive at the same endpoint but leave different histories..." value={claim} onChange={e=>setClaim(e.target.value)}/><h3>Check only what you can document.</h3><div className="check-list">{checks.map(c=><label className="check-row" key={c.id}><input type="checkbox" checked={!!checked[c.id]} onChange={e=>setChecked(v=>({...v,[c.id]:e.target.checked}))}/><span className="check-box"><Check size={13}/></span><span>{c.label}</span><b>+{c.weight}</b></label>)}</div><div className="actions"><button className="button primary" onClick={copyReport}><Clipboard size={17}/>{copied?"Copied!":"Copy evidence report"}</button><button className="button plain" onClick={()=>{setClaim("");setChecked({})}}>Reset</button></div></div><aside className="report" style={{"--heat":stage.color}}><span>YOUR SELF-ASSESSED SAUCE</span><div className="score">{points}<small>/ 100</small></div><div className="meter"><i style={{width:points+"%"}}/></div><div className="report-name"><Flame size={24}/><h3>{stage.name}</h3></div><p>{stage.sub}. Your documentation level changes as you tick the boxes.</p><div className="disclaimer"><ShieldCheck size={20}/><span>This is an educational, self-reported evidence checklist. It does not prove a claim true, detect misinformation, or certify research.</span></div><a className="text-button" target="_blank" rel="noreferrer" href={repo+"/issues/new?title="+encodeURIComponent("[Claim to Flame] Rubric suggestion")}>Suggest a rubric improvement <ArrowUpRight size={16}/></a></aside></div><ClaimArena bubbles={bubbles} receipts={evidenceEntries} reviews={reviewEntries} challenges={flameChallenges} feedStatus={feedStatus} onOpenRoom={openRoom}/><div className="society-foot">Presented by the Royal Society of Nested Bubble Bruvology<br/><strong>NO CITATION. NO CORONATION.</strong></div></section>}
  {page==="about"&&<section className="inner-page about"><Tag>WHY WE BUILT THE NEST</Tag><h1>A commons for <em>curious minds.</em></h1><p className="about-lead">Ideas shouldn't need a perfect pitch deck to find collaborators. They do need honesty about what is known, what's imagined, and who contributed what.</p><div className="principles">{[[Lightbulb,"Start messy","Questions, sketches, weird hypotheses and impossible inventions are welcome. Label speculation honestly."],[HeartHandshake,"Grow together","Build on each other's work with explicit credit. Collaborating does not automatically grant ownership."],[ShieldCheck,"Ledger above bruv","Record evidence, attribution, timestamps, test limitations, and corrections."],[Users,"Human + agent friendly","An open schema and GitHub workflow invite accountable contributions from people and agents."]].map(([Icon,title,body])=><div className="principle" key={title}><Icon size={28}/><h3>{title}</h3><p>{body}</p></div>)}</div><div className="about-box"><h2>The nest is open.<br/><em>The ledger is honest.</em></h2><p>Bubble Nest is a static, open-source React site. It doesn't secretly store public conversations or ask for access tokens. Publication and discussion live in GitHub Issues.</p><div className="actions"><button className="button primary" onClick={()=>setCompose(true)}>Start an idea <ArrowRight size={17}/></button><a className="button plain" href={repo} target="_blank" rel="noreferrer"><Github size={17}/> Browse source <ExternalLink size={15}/></a></div></div></section>}
  </main>
  <footer className="footer"><div className="brand"><Logo/><span><strong>bubble<span>nest</span></strong><small>Ideas find each other here.</small></span></div><div className="footer-nav"><a href="#/explore">Commons</a><a href="#/bubbleverse">Bubbleverse</a><a href="#/fusion">Bubble Fusion</a><a href="#/capsules">Capsule Lab</a><a href="#/flame">Claim to Flame</a><a href={repo} target="_blank" rel="noreferrer">GitHub <ExternalLink size={13}/></a></div><p>Enter the Field · Open collaboration · Sauce Before Source.<span>© 2026 Bubble Nest contributors · MIT</span></p></footer>
  {compose&&<div className="scrim" onMouseDown={e=>{if(e.target===e.currentTarget)setCompose(false)}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="compose-title"><div className="dialog-top"><div><Tag>YOUR NEXT BIG MAYBE</Tag><h2 id="compose-title">Start a <em>bubble.</em></h2></div><button className="close" aria-label="Close form" onClick={()=>setCompose(false)}><X size={22}/></button></div><p>Start with a question. Let collaborators help with the answers.</p><form onSubmit={e=>{e.preventDefault();save()}}><label className="field-label">Idea title *<input required maxLength="110" value={form.title} onChange={e=>change("title",e.target.value)} placeholder="What if we could..."/></label><label className="field-label">Category<select value={form.category} onChange={e=>change("category",e.target.value)}>{categories.filter(c=>c!=="All").map(c=><option key={c}>{c}</option>)}</select></label><label className="field-label">The spark *<textarea required rows="3" maxLength="1000" value={form.summary} onChange={e=>change("summary",e.target.value)} placeholder="Describe the idea, question or theory."/></label><label className="field-label">Why it matters<textarea rows="2" maxLength="700" value={form.why} onChange={e=>change("why",e.target.value)} placeholder="What makes this worth exploring?"/></label><label className="field-label">Collaboration request *<textarea required rows="2" maxLength="700" value={form.ask} onChange={e=>change("ask",e.target.value)} placeholder="Feedback, experiments, critique, collaborators..."/></label><label className="field-label">Evidence and limitations<textarea rows="2" maxLength="1000" value={form.evidence} onChange={e=>change("evidence",e.target.value)} placeholder="Links to evidence or clearly labeled speculation."/></label><div className="form-hint"><ShieldCheck size={16}/>Save in this browser, or review and publish via GitHub.</div><div className="dialog-actions"><button type="submit" className="button plain">Save private draft</button><button type="button" disabled={!canPost} className="button primary" onClick={publish}>Continue to GitHub <ArrowUpRight size={16}/></button></div></form></section></div>}
  {detail&&<div className="scrim" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><section className="dialog detail" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div className="dialog-top"><span className="pill">{detail.category}</span><button className="close" aria-label="Close details" onClick={()=>setDetail(null)}><X size={22}/></button></div><h2 id="detail-title">{detail.title}</h2><small>{detail.sample?"Illustrative example":detail.local?"Private draft":"Published by @"+detail.author}</small><h3>The spark</h3><p>{detail.summary}</p><h3>Collaboration request</h3><p>{detail.ask}</p><h3>Evidence and limitations</h3><p>{detail.evidence}</p><div className="dialog-actions"><button className="button primary" onClick={()=>openRoom(detail)}><Orbit size={16}/> Enter Bubble Room <ArrowRight size={16}/></button>{detail.url?<a className="button primary" target="_blank" rel="noreferrer" href={detail.url}>Discuss on GitHub <ArrowUpRight size={16}/></a>:detail.local?<button className="button primary" onClick={()=>{setForm({...blank,...detail});setDetail(null);setCompose(true)}}>Edit draft <ArrowRight size={16}/></button>:<button className="button primary" onClick={()=>{setDetail(null);setCompose(true)}}>Start a related bubble <Plus size={16}/></button>}</div></section></div>}
 </div>;
}
export default App;