import React,{useEffect,useMemo,useState} from "react";
import{ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,CalendarClock,CheckCircle2,ClipboardList,ExternalLink,FileText,Flame,FlaskConical,GitBranch,GitPullRequest,Info,Link2,MessageCircle,Orbit,Plus,Search,ShieldCheck,Sparkles,Users,X}from"lucide-react";
import {parseIssue} from "./data.js";
import EvolutionPanel,{EvolutionRail} from "./BubbleEvolution.jsx";
import EvidenceLedger from "./EvidenceLedger.jsx";
import BruvReviewDesk from "./BruvReviewDesk.jsx";
import {reviewsForBubble,reviewActivity,reviewAccounts} from "./reviewData.js";
import {evidenceForBubble,evidenceActivity,evidenceAccounts} from "./evidenceData.js";
import {evolutionActivity,evolutionAccounts,eventsForBubble} from "./evolutionData.js";
import {publicBubble} from "./bubbleGraph.js";
import {ROOM_KINDS,ROOM_STATES,makeRoomEntry,roomEntriesForBubble,roomActivity,roomParticipants} from "./roomData.js";
import "./rooms.css";
const REPO="https://github.com/MichaelWave369/bubblenest";
const emptyEntry={kind:"Experiment",status:"Proposed",summary:"",method:"",evidence:"",next:""};
const fmtDate=s=>{if(!s)return "Date unavailable";const d=new Date(s);return Number.isNaN(d.valueOf())?"Date unavailable":d.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"});};
function SmallLabel({children}){return <span className="room-eyebrow"><Sparkles size={13}/>{children}</span>}
function EntryCard({entry}){
 const Icon=entry.kind==="Experiment"?FlaskConical:entry.kind==="Reference"?BookOpen:GitBranch;
 return <article className="room-entry"><div className="room-entry-head"><span className="room-kind"><Icon size={15}/>{entry.kind}</span><span className="room-entry-status">{entry.status} · self-declared</span></div><h3>{entry.summary}</h3>{entry.method&&<p><strong>Method / context:</strong> {entry.method}</p>}{entry.evidence&&<p><strong>Evidence / limitations:</strong> {entry.evidence}</p>}{entry.next&&<p><strong>Next question:</strong> {entry.next}</p>}<div className="room-entry-footer"><span>By @{entry.author} · {fmtDate(entry.createdAt)} · GitHub {entry.issueState}</span><a href={entry.url} target="_blank" rel="noreferrer">Review contribution <ArrowUpRight size={15}/></a></div></article>;
}
function PanelEmpty({icon:Icon,title,description}){return <div className="room-blank"><Icon size={31}/><h3>{title}</h3><p>{description}</p></div>}
export default function BubbleRoom({bubble:known,roomId,allEntries,evolutionEvents=[],evidenceEntries=[],reviewEntries=[],feedStatus,onBack,onStart}){
 const[lookup,setLookup]=useState(null),[lookupStatus,setLookupStatus]=useState("idle");
 const[tab,setTab]=useState("Overview"),[writing,setWriting]=useState(false),[entry,setEntry]=useState(emptyEntry);
 useEffect(()=>{setTab("Overview");setWriting(false);setEntry(emptyEntry);setLookup(null);setLookupStatus("idle")},[roomId]);
 useEffect(()=>{
  if(known||!/^issue-[1-9]\d*$/.test(roomId)||lookupStatus!=="idle")return;
  const n=roomId.slice(6);let valid=true;
  setLookupStatus("loading");
  fetch("https://api.github.com/repos/MichaelWave369/bubblenest/issues/"+n,{headers:{Accept:"application/vnd.github+json"}})
   .then(r=>{if(!r.ok)throw Error("No public bubble at that issue number");return r.json()})
   .then(data=>{if(!valid)return;const found=parseIssue(data);setLookup(found);setLookupStatus(found?"ready":"unavailable")})
   .catch(()=>{if(valid)setLookupStatus("unavailable")});
  return()=>{valid=false};
 },[known,roomId,lookupStatus]);
 const bubble=known||lookup;
 const isPublic=publicBubble(bubble);
 const records=useMemo(()=>roomEntriesForBubble(allEntries,bubble),[allEntries,bubble]);
 const milestones=useMemo(()=>eventsForBubble(evolutionEvents,bubble),[evolutionEvents,bubble]);
 const receipts=useMemo(()=>evidenceForBubble(evidenceEntries,bubble),[evidenceEntries,bubble]);
 const reviews=useMemo(()=>reviewsForBubble(reviewEntries,bubble,evidenceEntries),[reviewEntries,bubble,evidenceEntries]);
 const[reviewTarget,setReviewTarget]=useState(null);
 useEffect(()=>setReviewTarget(null),[roomId]);
 const activity=useMemo(()=>[...roomActivity(bubble,records),...evolutionActivity(evolutionEvents,bubble),...evidenceActivity(evidenceEntries,bubble),...reviewActivity(reviewEntries,bubble,evidenceEntries)].sort((a,b)=>(b.date||"").localeCompare(a.date||"")||a.id.localeCompare(b.id)),[bubble,records,evolutionEvents,evidenceEntries,reviewEntries]);
 const contributors=useMemo(()=>[...new Set([...roomParticipants(bubble,records),...evolutionAccounts(evolutionEvents,bubble),...evidenceAccounts(evidenceEntries,bubble),...reviewAccounts(reviewEntries,bubble,evidenceEntries)])].sort(),[bubble,records,evolutionEvents,evidenceEntries,reviewEntries]);
 const related=useMemo(()=>records.filter(r=>tab==="Experiments"?r.kind==="Experiment":tab==="References"?r.kind==="Reference":true),[records,tab]);
 const draft=bubble&&isPublic?makeRoomEntry({...entry,bubble}):null;
 const modify=(key,value)=>setEntry(e=>({...e,[key]:value}));
 const startKind=kind=>{setEntry({...emptyEntry,kind});setWriting(true);};
 if(!bubble)return <section className="inner-page room-page"><button className="room-back" onClick={onBack}><ArrowLeft size={17}/> Return to ideas</button><div className="room-not-found"><Orbit size={42}/><h1>{feedStatus==="loading"||lookupStatus==="loading"?"Finding your bubble…":"Bubble not found."}</h1><p>{feedStatus==="loading"||lookupStatus==="loading"?"Retrieving public contributions.":"The link may be incorrect, the bubble may have been removed, or GitHub may be unavailable. No data was fabricated."}</p><button className="button primary" onClick={onBack}>Explore the commons <ArrowRight size={17}/></button></div></section>;
 return <section className="inner-page room-page">
  <button className="room-back" onClick={onBack}><ArrowLeft size={17}/> Back to the commons</button>
  <div className="room-banner"><div className="room-banner-copy"><SmallLabel>YOUR IDEA HAS ROOM TO GROW</SmallLabel><div className="room-status-line"><span>{bubble.category}</span><span>·</span><span>{bubble.sample?"Illustrative example":bubble.local?"Private browser draft":"Public GitHub bubble"}</span></div><h1>{bubble.title}</h1><p>{bubble.summary}</p><div className="room-banner-actions">{isPublic?<a className="button primary" href={bubble.url} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Join GitHub discussion <ExternalLink size={16}/></a>:<button className="button primary" onClick={onStart}><Plus size={17}/> {bubble.local?"Review or publish an idea":"Start a real bubble"}</button>}<a className="button plain" href={"#/flame?bubble="+encodeURIComponent(bubble.id)}><Flame size={17}/> Claim to Flame Arena <ArrowUpRight size={15}/></a><button className="button plain" onClick={()=>document.getElementById("room-records")?.scrollIntoView({behavior:"smooth"})}><ClipboardList size={17}/> Research notes <ArrowRight size={17}/></button></div></div><div className="room-art" aria-hidden="true"><span className="room-ring ring-out"/><span className="room-ring ring-in"/><span className="room-star star-one"/><span className="room-star star-two"/><Orbit size={76}/></div></div>
  <div className="room-overview-grid"><div className="room-mini-stat"><FlaskConical size={20}/><strong>{records.filter(r=>r.kind==="Experiment").length}</strong><span>Proposed experiments</span></div><div className="room-mini-stat"><BookOpen size={20}/><strong>{records.filter(r=>r.kind==="Reference").length}</strong><span>Shared references</span></div><div className="room-mini-stat"><GitBranch size={20}/><strong>{receipts.length}</strong><span>Evidence receipts</span></div><div className="room-mini-stat"><Users size={20}/><strong>{isPublic?contributors.length:0}</strong><span>{isPublic?"Recorded accounts":"Public contributors"}</span></div></div>
  <EvolutionRail bubble={bubble} events={evolutionEvents} onView={()=>{setTab("Evolution");document.getElementById("room-records")?.scrollIntoView({behavior:"smooth"})}}/>
  <div className="room-layout" id="room-records"><div className="room-primary">
   <div className="room-tabs" role="tablist" aria-label="Research room sections">{["Overview","Evolution","Evidence","Bruv Review","Experiments","References","Activity"].map(t=><button type="button" role="tab" aria-selected={tab===t} key={t} className={tab===t?"selected":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
   {tab==="Evolution"&&<EvolutionPanel bubble={bubble} events={evolutionEvents} feedStatus={feedStatus}/>}
   {tab==="Evidence"&&<EvidenceLedger bubble={bubble} entries={evidenceEntries} feedStatus={feedStatus} onReview={id=>{setReviewTarget(id);setTab("Bruv Review")}}/>}
   {tab==="Bruv Review"&&<BruvReviewDesk bubble={bubble} receipts={evidenceEntries} reviews={reviewEntries} initialReceipt={reviewTarget} feedStatus={feedStatus}/>}
   {tab==="Overview"&&<div className="room-panel"><SmallLabel>ROOM DOSSIER</SmallLabel><h2>Where the work begins.</h2><section className="room-dossier"><h3>The collaboration request</h3><p>{bubble.ask||"Open for discussion."}</p><h3>Current evidence & limitations</h3><p>{bubble.evidence||"No evidence has been recorded."}</p></section><h3 className="room-list-heading">Recent public records</h3><p>{milestones.length} evolution event(s), {receipts.length} evidence receipt(s), and {reviews.length} review(s) tracked in their dedicated tabs.</p>{records.length?<>{records.slice(0,3).map(r=><EntryCard entry={r} key={r.id}/>)}</>:<PanelEmpty icon={FileText} title="The research ledger starts here." description={isPublic?"Add a proposed experiment, source, or update through GitHub. Nothing is verified automatically.":"This is an idea preview. Only published GitHub bubbles have shared research ledgers."}/>}</div>}
   {["Experiments","References"].includes(tab)&&<div className="room-panel"><SmallLabel>{tab==="Experiments"?"HYPOTHESES AND REPEATABLE TESTS":"THE SOURCE SHELF"}</SmallLabel><div className="room-section-heading"><div><h2>{tab==="Experiments"?"Experiment bench":"Reference shelf"}</h2><p>{tab==="Experiments"?"Proposed tests and their self-reported progress, linked to the originating bubble.":"Sources and context submitted by participants, not automatically endorsed."}</p></div>{isPublic&&<button className="room-small-cta" onClick={()=>startKind(tab==="Experiments"?"Experiment":"Reference")}><Plus size={16}/> Propose</button>}</div>{related.length?related.map(r=><EntryCard key={r.id} entry={r}/>):<PanelEmpty icon={tab==="Experiments"?FlaskConical:BookOpen} title={tab==="Experiments"?"No public experiments yet":"No public references yet"} description={isPublic?"Be the first to propose an attributable record in GitHub.":"Preview ideas cannot collect public submissions until published."}/>}</div>}
   {tab==="Activity"&&<div className="room-panel"><SmallLabel>ATTRIBUTION AND HISTORY</SmallLabel><h2>The visible record.</h2><p>GitHub timestamps identify when records were submitted. This is not an exhaustive audit of edits or proof of intellectual origin.</p>{activity.length?<ol className="room-activity">{activity.map(a=><li key={a.id}><div className="room-activity-icon"><CalendarClock size={16}/></div><div><span>{fmtDate(a.date)} · {a.type}</span><strong>{a.description}</strong><small>GitHub account: @{a.author}</small>{a.url&&<a href={a.url} target="_blank" rel="noreferrer">Open public receipt <ArrowUpRight size={14}/></a>}</div></li>)}</ol>:<PanelEmpty icon={CalendarClock} title="No public record yet" description="Publish the bubble to create a public, timestamped GitHub discussion."/>}</div>}
   {isPublic&&<div className="room-add-box"><div><SmallLabel>BRING YOUR SAUCE</SmallLabel><h3>Build on this idea.</h3><p>Propose experiments, add references, or record an update. You'll review the full entry on GitHub before submitting.</p></div><button className="button primary" onClick={()=>setWriting(v=>!v)}>{writing?<X size={17}/>:<Plus size={17}/>} {writing?"Close form":"Add contribution"}</button></div>}
   {writing&&isPublic&&<form className="room-form" onSubmit={e=>e.preventDefault()}><div className="room-form-head"><h3>Propose a public contribution</h3><p>Your draft stays on this page until you choose to open GitHub. No silent publishing.</p></div><div className="room-form-grid"><label className="field-label">Contribution type<select value={entry.kind} onChange={e=>modify("kind",e.target.value)}>{ROOM_KINDS.map(k=><option key={k}>{k}</option>)}</select></label><label className="field-label">Self-reported status<select value={entry.status} onChange={e=>modify("status",e.target.value)}>{ROOM_STATES.map(s=><option key={s}>{s}</option>)}</select></label></div><label className="field-label">Short summary *<input required maxLength={250} value={entry.summary} onChange={e=>modify("summary",e.target.value)} placeholder="What should others know?"/></label><label className="field-label">Method, context, or source description<textarea maxLength={750} rows={3} value={entry.method} onChange={e=>modify("method",e.target.value)} placeholder="Steps to test it, source title, or update context…"/></label><label className="field-label">Evidence, links & limitations<textarea maxLength={750} rows={3} value={entry.evidence} onChange={e=>modify("evidence",e.target.value)} placeholder="Public URLs, observations, or clearly marked uncertainty…"/></label><label className="field-label">Next question<textarea maxLength={500} rows={2} value={entry.next} onChange={e=>modify("next",e.target.value)} placeholder="What is left to check or try?"/></label><div className="room-form-footer"><p><ShieldCheck size={17}/> A proposal is never automatic proof. GitHub sign-in is needed to post.</p>{draft?<a className="button primary" href={draft.url} target="_blank" rel="noreferrer">Review in GitHub <ArrowUpRight size={16}/></a>:<button type="button" className="button primary" disabled>Enter a summary first</button>}</div></form>}
  </div>
  <aside className="room-sidebar"><div className="room-side-panel"><SmallLabel>CONTRIBUTION LEDGER</SmallLabel><h3>Who is in this room?</h3>{isPublic&&contributors.length?<div className="room-people">{contributors.map((p,i)=><div key={p}><span className="room-avatar">{p.slice(0,1).toUpperCase()}</span><span><strong>@{p}</strong><small>{p===bubble.author?"Bubble author":"Public record participant"}</small></span></div>)}</div>:<p>Contributors appear only after publicly attributable GitHub activity. No imaginary members.</p>}<p className="room-fine">This list is based on visible issue authors, not a formal collaborator or authorship registry.</p></div><div className="room-side-panel"><SmallLabel>THE REALITY GATE</SmallLabel><h3>Sauce Before Source.</h3><p>Separate someone's proposal from a validated result. Record your references. Respect independent ideas.</p><div className="room-rule"><CheckCircle2 size={16}/> Proposed ≠ proven</div><div className="room-rule"><ShieldCheck size={16}/> Attribution stays visible</div><div className="room-rule"><Info size={16}/> Disagreement is welcome</div></div><div className="room-side-panel"><SmallLabel>PUBLIC STORAGE</SmallLabel><h3>GitHub is the ledger.</h3><p>Public contributions live as separate GitHub Issues referencing this bubble. They remain inspectable and commentable even after an issue is closed, within the site's fetch limits.</p>{isPublic&&<a className="room-side-link" href={bubble.url} target="_blank" rel="noreferrer">Open the parent issue <ExternalLink size={15}/></a>}</div></aside></div>
  <div className="room-notice"><Info size={19}/><p><strong>Truth in labeling:</strong> {bubble.sample?"This is sample content, not a published research project. ":bubble.local?"This is a local draft, not a public research room. ":"Entries are publicly submitted claims, not independently verified results. "}Community records come from GitHub Issues. The site cannot guarantee that every issue or edit has been fetched, and it does not confer authorship, certification, or ownership.</p></div>
 </section>;
}
