import React,{useMemo,useState,useEffect} from "react";
import{ArrowUpRight,BookOpen,Check,ChevronRight,CircleHelp,Clock3,ExternalLink,FileCheck2,FlaskConical,GitBranch,History,Lightbulb,Plus,RefreshCw,ShieldCheck,Sparkles,X}from"lucide-react";
import {EVOLUTION_STAGES,EVOLUTION_OUTCOMES,makeEvolutionDraft,eventsForBubble,currentEvolution}from"./evolutionData.js";
import {publicBubble} from "./bubbleGraph.js";
import "./evolution.css";

const Icons={Spark:Lightbulb,Hypothesis:CircleHelp,Experiment:FlaskConical,Evidence:FileCheck2,Revision:RefreshCw};
const blank={stage:"Hypothesis",outcome:"Proposal",statement:"",method:"",limits:"",next:""};
const dateLabel=s=>{const d=new Date(s||"");return !Number.isNaN(d.getTime())?d.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"Date unavailable";};
export function EvolutionRail({events,bubble,onView}){
 const progress=currentEvolution(events,bubble);
 const reached=new Set(progress.stagesWithRecords);
 return <div className="ev-rail-wrap"><div className="ev-rail-heading"><div><span className="room-eyebrow"><GitBranch size={13}/> EVOLUTION JOURNEY</span><h2>The path is the story.</h2><p>Milestones are documented contributions, not grades, certifications or a required linear sequence.</p></div><button className="ev-open" onClick={onView}>View evolution ledger <ChevronRight size={16}/></button></div><div className="ev-rail" aria-label="Five possible stages of idea development">{EVOLUTION_STAGES.map((s,i)=>{const Icon=Icons[s.id];const used=reached.has(s.id);return <div className="ev-step" key={s.id}><div className={"ev-step-symbol "+(used?"logged":"")}><Icon size={21}/></div><span>{String(i+1).padStart(2,"0")}</span><strong>{s.id}</strong><small>{used?"Contributor record":"No stage record"}</small></div>})}</div><div className="ev-current"><span className="ev-spark"/> <strong>{progress.reported?"Most recently reported stage: "+progress.stage:"Starting point: Spark"}</strong><span>{progress.reported?progress.count+" public contributor record(s)":"No evolution reports yet"}</span></div></div>;
}
export default function EvolutionPanel({events,bubble,feedStatus}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(blank),[stageFilter,setStageFilter]=useState("All");
 useEffect(()=>{setOpen(false);setDraft(blank);setStageFilter("All")},[bubble?.id]);
 const publicRoom=publicBubble(bubble),records=useMemo(()=>eventsForBubble(events,bubble),[events,bubble]);
 const state=currentEvolution(events,bubble);
 const list=records.filter(e=>stageFilter==="All"||e.stage===stageFilter).slice().reverse();
 const published=makeEvolutionDraft({...draft,bubble});
 const update=(name,value)=>setDraft(d=>({...d,[name]:value}));
 return <div className="ev-panel"><div className="ev-panel-head"><div><span className="room-eyebrow"><History size={13}/> RESEARCH EVOLUTION LEDGER</span><h2>How this idea changes.</h2><p>Hypotheses can become experiments, evidence can challenge them, and revisions can send us back to earlier stages. There is no automatic certification or forced progression.</p></div><div className="ev-current-stage"><span>LATEST REPORTED STAGE</span><strong>{state.stage}</strong><small>{state.reported?"Self-reported in GitHub":"Starting assumption only"}</small></div></div>
  <div className="ev-explain"><ShieldCheck size={19}/><span>Evidence means <strong>someone submitted documentation</strong>, not that independent reviewers have validated the result. Every event has its own public receipt when available.</span></div>
  <div className="ev-stage-guide">{EVOLUTION_STAGES.map(s=>{const Icon=Icons[s.id],used=state.stagesWithRecords.includes(s.id);return <button key={s.id} type="button" className={"ev-stage-guide-item "+(stageFilter===s.id?"selected":"")} onClick={()=>setStageFilter(f=>f===s.id?"All":s.id)} aria-pressed={stageFilter===s.id}><Icon size={19}/><strong>{s.id}</strong><small>{s.detail}</small><span>{used?"Record present":"Not recorded"}</span></button>})}</div>
  <div className="ev-entries-heading"><div><h3>Public evolution notes</h3><p>Chronological records, newest first. Use a stage above to filter.</p></div><span>{list.length} shown</span></div>
  {list.length?<div className="ev-log">{list.map(e=><article key={e.id} className="ev-event"><span className="ev-event-dot"/><div className="ev-event-body"><div className="ev-event-label"><strong>{e.stage}</strong><span>{e.outcome} · contributor-reported</span></div><h4>{e.statement}</h4>{e.method&&<p><b>Method / receipts:</b> {e.method}</p>}<p><b>Uncertainty:</b> {e.limits}</p>{e.next&&<p><b>Next question:</b> {e.next}</p>}<div className="ev-event-meta"><span><Clock3 size={14}/>{dateLabel(e.date)} · @{e.author}</span><a href={e.url} target="_blank" rel="noreferrer">Inspect GitHub receipt <ArrowUpRight size={14}/></a></div></div></article>)}</div>:<div className="ev-empty"><GitBranch size={33}/><h3>{stageFilter!=="All"?"No "+stageFilter+" entries yet":"No recorded evolution yet"}</h3><p>{publicRoom?"Be the first to describe a hypothesis, experiment, observation or revision, with explicit limitations.":"This room is illustrative or browser-local. Public records require a published GitHub bubble."}</p></div>}
  {publicRoom?<><div className="ev-add-row"><div><span className="room-eyebrow"><Sparkles size={13}/> DOCUMENT THE NEXT CHANGE</span><h3>Record a milestone.</h3><p>Each entry opens a prefilled public GitHub Issue. Nothing is published without your own submission.</p></div><button className="button primary" type="button" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?"Close":"Add stage record"}</button></div>
  {open&&<form className="ev-form" onSubmit={e=>e.preventDefault()}><div className="ev-form-columns"><label className="field-label">Stage<select value={draft.stage} onChange={e=>update("stage",e.target.value)}>{EVOLUTION_STAGES.map(s=><option key={s.id}>{s.id}</option>)}</select></label><label className="field-label">Contributor classification<select value={draft.outcome} onChange={e=>update("outcome",e.target.value)}>{EVOLUTION_OUTCOMES.map(o=><option key={o}>{o}</option>)}</select></label></div>
   <label className="field-label">What claim or change are you recording? *<textarea rows={3} maxLength={900} value={draft.statement} onChange={e=>update("statement",e.target.value)} placeholder="State the specific idea, test, observation or revision…"/></label>
   <label className="field-label">Method, observations, source links {["Experiment","Evidence"].includes(draft.stage)?"*":""}<textarea rows={3} maxLength={1200} value={draft.method} onChange={e=>update("method",e.target.value)} placeholder="Reproducible steps, public references or details of the work…"/></label>
   <label className="field-label">Limitations, uncertainty or alternative explanation *<textarea rows={3} maxLength={900} value={draft.limits} onChange={e=>update("limits",e.target.value)} placeholder="What remains unknown, unsupported, biased, or worth challenging?"/></label>
   <label className="field-label">Next question<textarea rows={2} maxLength={800} value={draft.next} onChange={e=>update("next",e.target.value)} placeholder="What would you or another contributor try next?"/></label>
   <div className="ev-form-bottom"><p><ShieldCheck size={16}/> You must review and submit the Issue while signed in to GitHub. A reported result is not a verified result.</p>{published?<a className="button primary" href={published.url} target="_blank" rel="noreferrer">Review on GitHub <ExternalLink size={15}/></a>:<button className="button primary" disabled type="button">Complete required fields</button>}</div></form>}</>:<div className="ev-preview-note"><BookOpen size={18}/> Public evolution records are available only after you publish a Bubble Nest idea through GitHub.</div>}
  {feedStatus==="unavailable"&&<p className="ev-warning">GitHub's feed is unavailable. Existing public records may not be visible right now; a blank ledger is not proof that no records exist.</p>}
 </div>;
}
